LeaSaraa/Karma_connect

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_logo.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_site.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

Hey girls
So this is the navbar and footer design
The links in the footer lead nowhere for the moment, I wanted to wait for the correponding views to be created so that it doesn't crash

Guerrique navbar footer design

---

db/data/user1.yml
db/data/user2.yml
db/migrate/20190527125215_add_photo_to_articles.rb
db/seeds.rb

- Added the seeds in seeds.rb file.
- The data you will find in the Data folder.
As far as I can see everything is working. I've tested and so far so good. However, please keep an eye on the picture uploader in the Post table. Let me know if it does not work well and I will fix this.

Creating seeds

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_post.scss
app/assets/stylesheets/pages/_posts.scss
app/views/my_posts/new.html.erb

Did the styling for the new post page, looks almost like the figma page.
But before the end we will have to see if this design is ok, feels a bit to simple now.. 
I removed the button preview for the moment

create new post styling

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_map.scss
app/controllers/posts_controller.rb
app/views/posts/_list.html.erb
app/views/posts/show.html.erb
config/routes.rb

Did the design of the single post page
Was giving weird results on chrome sometimes... We will have to check that!

Guerrique design single post page

---

app/views/posts/_list.html.erb

Hello
So implemented the map on the post show page. It is not static though.
And did an invisible log out button on top right corner

line deleted on list post page

---

app/views/shared/_footer.html.erb

yes, it was about syntax to link
use the rails helpers instead of a href

problem of link to post creation solved

---

app/controllers/comments_controller.rb
app/controllers/posts_controller.rb
app/controllers/users_controller.rb
app/models/comment.rb
app/models/post.rb
app/views/comments/_form.html.erb
app/views/comments/create.js.erb
app/views/posts/show.html.erb
config/routes.rb
db/migrate/20190530103924_create_comments.rb
db/schema.rb
test/controllers/comments_controller_test.rb
test/models/comment_test.rb

Comments post

---

app/controllers/my_posts_controller.rb

User id error corrected

---

Active
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_my-posts.scss
app/assets/stylesheets/pages/_post.scss
app/controllers/my_posts_controller.rb
app/controllers/posts_controller.rb
app/views/my_posts/index.html.erb
app/views/posts/_list.html.erb
app/views/posts/show.html.erb
app/views/users/show.html.erb
db/migrate/20190530181445_change_column.rb
db/schema.rb

Did the styling for the pop up to change post status.
Not finished yet, will need to add some javascript maybe, and surely add the part where the user can give Karma points

Guerrique styling post status

---

app/controllers/comments_controller.rb
app/views/comments/_form.html.erb
app/views/comments/create.js.erb
app/views/posts/_show.html.erb
app/views/posts/show.html.erb
db/schema.rb

Comment load without refreshing the page

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_comment.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_post.scss
app/controllers/comments_controller.rb
app/models/comment.rb
app/views/comments/_form.html.erb
app/views/comments/create.js.erb
app/views/posts/_comment.html.erb
app/views/posts/_list.html.erb
app/views/posts/_show.html.erb
app/views/posts/show.html.erb
db/migrate/20190531111339_add_user_to_comments.rb
db/schema.rb

Comments now arrive with style! Thanks Lars!!
Added a relationship between comment table and user

comment styling

---

app/views/chatrooms/show.html.erb
db/data/user11.yml
db/data/user12.yml
db/data/user13.yml
db/data/user14.yml
db/data/user15.yml
db/seeds.rb

Updated the seeds, added a few

updated the seeds

---

app/assets/stylesheets/components/_chatroom.scss
app/views/chatrooms/index.html.erb
app/views/chatrooms/show.html.erb
app/views/messages/_message_form.html.erb

Frontend Chatbox

---

app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/pages/_post.scss
app/assets/stylesheets/pages/_posts.scss
app/assets/stylesheets/pages/_site.scss
app/views/posts/_map.html.erb
app/views/posts/show.html.erb
db/data/user10.yml
db/data/user11.yml

Beginning of styling of post page
Trying to fix seed n10, some other seeds are not working, we have to check it out

Guerrique monday posts index

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_star.scss
app/views/compliments/new.html.erb
app/views/pages/home.html.erb

Stars working

---

app/assets/stylesheets/components/_star.scss

Colours changed in line with page

---

app/assets/stylesheets/components/_compliment.scss
app/views/users/_userpage.html.erb

Compliments display improved

---

db/data/user10.yml
db/data/user12.yml
db/data/user4.yml
db/data/user7.yml
db/data/user8.yml

address fixed

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_infowindow.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_modal.scss
app/assets/stylesheets/pages/_posts.scss
app/assets/stylesheets/pages/_userpage.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/my_posts/index.html.erb
app/views/posts/_infowindow.html.erb
db/data/user3.yml

styling for post management popup, map info window, log in and sign in pages

a few stylings

---

app/controllers/application_controller.rb
app/helpers/meta_tags_helper.rb
app/views/layouts/application.html.erb
config/initializers/default_meta.rb
config/meta.yml

meta done no twitter and facebook page yet

meta tags done
